# Merging Allocs Files from ITI Files
Taking multipe allocs files from iti.files Qgroundcontrol Allocs folder and merging them together

Needed to run some extra code to assure columns match up correctly with their values and to remove extra column. Also had to remove filler 14 from alloc_ip column.

In [1]:
# imports here
import pandas as pd
import numpy as np

In [2]:
mergeddf = pd.concat( 
    map(pd.read_csv, ['v20.6.6.3.enable2.QGroundControl.allocs',
    'v20.6.6.3.enable1.QgroundControl.allocs',
    'v20.6.1.60.enable2.QgroundControl.allocs',
    'v20.6.1.60.enable1.QgroundControl.allocs',
    'v20.6.1.38.enable2.Qgroundcontrol.allocs',
    'v20.6.1.38.enable1.Qgroundcontrol.allocs',
    'Sept14.r13.run2.QgroundControl.allocs',
    'Sept14.r13.run1.QgroundControl.allocs',
    'Sept13.r12.QgroundControl.allocs',
    'Oct14.r11.3.Qgroundcontrol.allocs',
    'Nov7.r11.3.QgroundControl.allocs',
    'Nov6.r17.QgroundControl.allocs',
    'notfromFreshBoot.v20.6.6.3.enable2.QGroundControl.allocs',
    '6.6.3.v20.23.10.distro.enable1.QgroundControl.allocs'])).reset_index()
mergeddf.head()

,index,alloc_ip,pid,ptr,size,alloc_serial,free_serial,free_ip,type,slab,new_type,alloc_jiffies,free_jiffies
0,14,2370,ffff8881a8ea799b,1,152,312.0,00000000deadbeef,UFO_MEMBLOCK,bash,no-slab,UFO_MEMBLOCK,NaN,NaN
1,14,2370,ffff88815a2b6794,4,170,46208.0,00000000deadbeef,UFO_MEMBLOCK,bash,filp,KMEM_CACHE_BULK,NaN,NaN
2,14,2370,ffff88815a2b6820,8,171,46208.0,00000000deadbeef,UFO_MEMBLOCK,bash,filp,KMEM_CACHE_BULK,NaN,NaN
3,14,2370,ffff88815a2b6828,8,177,46208.0,00000000deadbeef,UFO_MEMBLOCK,bash,filp,KMEM_CACHE_BULK,NaN,NaN
4,14,2370,ffff88815a2b67c0,8,181,46208.0,00000000deadbeef,UFO_MEMBLOCK,bash,filp,KMEM_CACHE_BULK,NaN,NaN

In [45]:
df = mergeddf
df.head()

,index,alloc_ip,pid,ptr,size,alloc_serial,free_serial,free_ip,type,slab,new_type,alloc_jiffies,free_jiffies
0,14,2370,ffff8881a8ea799b,1,152,312.0,00000000deadbeef,UFO_MEMBLOCK,bash,no-slab,UFO_MEMBLOCK,NaN,NaN
1,14,2370,ffff88815a2b6794,4,170,46208.0,00000000deadbeef,UFO_MEMBLOCK,bash,filp,KMEM_CACHE_BULK,NaN,NaN
2,14,2370,ffff88815a2b6820,8,171,46208.0,00000000deadbeef,UFO_MEMBLOCK,bash,filp,KMEM_CACHE_BULK,NaN,NaN
3,14,2370,ffff88815a2b6828,8,177,46208.0,00000000deadbeef,UFO_MEMBLOCK,bash,filp,KMEM_CACHE_BULK,NaN,NaN
4,14,2370,ffff88815a2b67c0,8,181,46208.0,00000000deadbeef,UFO_MEMBLOCK,bash,filp,KMEM_CACHE_BULK,NaN,NaN

In [46]:
df = df.rename(columns = {'index': 'alloc_ip','alloc_ip': 'pid','pid': 'ptr','ptr': 'size','size': 'alloc_serial','alloc_serial': 'free_serial','free_serial': 'free_ip','free_ip': 'type','type': 'command','slab':'slab','new_type':'new_type'})
df.head()

,alloc_ip,pid,ptr,size,alloc_serial,free_serial,free_ip,type,command,slab,new_type,alloc_jiffies,free_jiffies
0,14,2370,ffff8881a8ea799b,1,152,312.0,00000000deadbeef,UFO_MEMBLOCK,bash,no-slab,UFO_MEMBLOCK,NaN,NaN
1,14,2370,ffff88815a2b6794,4,170,46208.0,00000000deadbeef,UFO_MEMBLOCK,bash,filp,KMEM_CACHE_BULK,NaN,NaN
2,14,2370,ffff88815a2b6820,8,171,46208.0,00000000deadbeef,UFO_MEMBLOCK,bash,filp,KMEM_CACHE_BULK,NaN,NaN
3,14,2370,ffff88815a2b6828,8,177,46208.0,00000000deadbeef,UFO_MEMBLOCK,bash,filp,KMEM_CACHE_BULK,NaN,NaN
4,14,2370,ffff88815a2b67c0,8,181,46208.0,00000000deadbeef,UFO_MEMBLOCK,bash,filp,KMEM_CACHE_BULK,NaN,NaN

In [47]:
df = df.drop(df[df['alloc_ip'] == '14              '].index)
df

,alloc_ip,pid,ptr,size,alloc_serial,free_serial,free_ip,type,command,slab,new_type,alloc_jiffies,free_jiffies
41,ffffffff8164f7c2,2370,ffff8881a8eb6000,2048,1162,1163.0,000000000fedbeef,KMEM_CACHE_BULK,bash,kmalloc-1k,KMALLOC_ND,NaN,NaN
198,18,0,ffffffff8966b468,1,5542,5546.0,00000000deadbeef,UFO_GLOBAL,softirq,no-slab,UFO_GLOBAL,NaN,NaN
199,ffffffff8164f7c2,0,ffff8881a8e28c00,256,5713,5714.0,000000000fedbeef,KMEM_CACHE_BULK,softirq,kmalloc-128,KMALLOC_ND,NaN,NaN
200,ffffffff825866e4,0,ffff8881a8e28c00,256,5714,9796.0,ffffffff8258ca49,KMALLOC_ND,softirq,kmalloc-128,NaN,NaN,NaN
263,ffffffff82799aca,0,ffff88816f098b40,320,6351,428052.0,ffffffff827905f1,KMEM_CACHE_BULK,softirq,skbuff_head_cache,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15494152,ffffffff817ea563,2873,ffff888101184400,4352,2240925,2240929.0,ffffffff817e889d,KMEM_CACHE_BULK,QGroundControl,names_cache,NaN,NaN,NaN
15494153,ffffffff81b3dcef,2873,ffff8881c691b600,48,2240927,2240970.0,ffffffff81b3c766,KMEM_CACHE_BULK,QGroundControl,lsm_file_cache,NaN,NaN,NaN
15494154,ffffffff817ea563,2873,ffff888101184400,4352,2240932,2240968.0,ffffffff817e889d,KMEM_CACHE_BULK,QGroundControl,names_cache,NaN,NaN,NaN
15494155,ffffffff8278d9e4,0,ffff8881c6949e00,320,2240950,2240958.0,ffffffff82793536,KMEM_CACHE_BULK,softirq,skbuff_head_cache,NaN,NaN,NaN
15494156,ffffffff817ea563,2701,ffff888101184400,4352,2240978,2241055.0,ffffffff817e889d,KMEM_CACHE_BULK,bash,names_cache,NaN,NaN,NaN

In [48]:
print('Number of Rows:', df.shape[0])
print('Number of Columns:', df.shape[1])

Number of Rows: 14867950
Number of Columns: 13

In [50]:
df = df.copy()
df['alloc_jiffies'].fillna(df['alloc_serial'], inplace=True)
df['free_ip'].fillna(df['free_jiffies'], inplace=True)
df = df.drop(columns = ['alloc_serial','free_jiffies'])
df = df.rename(columns = {'free_serial':'free_jiffies'})
df.head()

C:\Users\gimli\AppData\Local\Temp\ipykernel_2472\2127304783.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['alloc_jiffies'].fillna(df['alloc_serial'], inplace=True)
C:\Users\gimli\AppData\Local\Temp\ipykernel_2472\2127304783.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['free_ip'].fillna(df['free_jiffies'], inplace=True)

,alloc_ip,pid,ptr,size,free_jiffies,free_ip,type,command,slab,new_type,alloc_jiffies
41,ffffffff8164f7c2,2370,ffff8881a8eb6000,2048,1163.0,000000000fedbeef,KMEM_CACHE_BULK,bash,kmalloc-1k,KMALLOC_ND,1162.0
198,18,0,ffffffff8966b468,1,5546.0,00000000deadbeef,UFO_GLOBAL,softirq,no-slab,UFO_GLOBAL,5542.0
199,ffffffff8164f7c2,0,ffff8881a8e28c00,256,5714.0,000000000fedbeef,KMEM_CACHE_BULK,softirq,kmalloc-128,KMALLOC_ND,5713.0
200,ffffffff825866e4,0,ffff8881a8e28c00,256,9796.0,ffffffff8258ca49,KMALLOC_ND,softirq,kmalloc-128,NaN,5714.0
263,ffffffff82799aca,0,ffff88816f098b40,320,428052.0,ffffffff827905f1,KMEM_CACHE_BULK,softirq,skbuff_head_cache,NaN,6351.0

In [51]:
df.to_csv('onlinefilesdatabase.csv')

In [52]:
newdf = pd.read_csv('onlinefilesdatabase.csv')
newdf.head()

,Unnamed: 0,alloc_ip,pid,ptr,size,free_jiffies,free_ip,type,command,slab,new_type,alloc_jiffies
0,41,ffffffff8164f7c2,2370,ffff8881a8eb6000,2048,1163.0,000000000fedbeef,KMEM_CACHE_BULK,bash,kmalloc-1k,KMALLOC_ND,1162.0
1,198,18,0,ffffffff8966b468,1,5546.0,00000000deadbeef,UFO_GLOBAL,softirq,no-slab,UFO_GLOBAL,5542.0
2,199,ffffffff8164f7c2,0,ffff8881a8e28c00,256,5714.0,000000000fedbeef,KMEM_CACHE_BULK,softirq,kmalloc-128,KMALLOC_ND,5713.0
3,200,ffffffff825866e4,0,ffff8881a8e28c00,256,9796.0,ffffffff8258ca49,KMALLOC_ND,softirq,kmalloc-128,NaN,5714.0
4,263,ffffffff82799aca,0,ffff88816f098b40,320,428052.0,ffffffff827905f1,KMEM_CACHE_BULK,softirq,skbuff_head_cache,NaN,6351.0