# Merging the CSV Files Together
Attempting to merge together my separate csv files to create a big database of the online iti files and the desktop files

In [1]:
# imports here
import pandas as pd
import numpy as np

In [4]:
df = pd.concat( 
    map(pd.read_csv, ['/Users/gimli/Desktop/mergeddatabase/allocs/folderdatabase.csv',
    '/Users/gimli/Desktop/mergeddatabase/Qgroundcontrol Allocs/onlinefilesdatabase.csv']))
df.head()

,Unnamed: 0,alloc_ip,pid,ptr,size,alloc_jiffies,free_jiffies,free_ip,type,command,slab,new_type
0,25,ffffffff81a5ba8f,226,ffff88818dc853f0,176,25383.0,211939.0,00000000deadbeef,KMEM_CACHE_BULK,systemd-journal,jbd2_journal_head,KMEM_CACHE_BULK
1,57,ffffffff817204a4,2203,ffff8881b1640000,4096,48840.0,197120.0,ffffffff816d38f4,ALLOC_PAGES_FOLIO,bash,no-slab,NaN
2,64,ffffffff817cf984,2348,ffff888185d79b80,320,61904.0,211790.0,ffffffff817cf0b7,KMEM_CACHE_BULK,less,filp,NaN
3,65,ffffffff817cf984,2348,ffff888185d78280,320,61906.0,211768.0,ffffffff817cf0b7,KMEM_CACHE_BULK,less,filp,NaN
4,66,ffffffff811733c8,2348,ffff8881921a0000,6912,61911.0,196022.0,00000000deadbeef,KMEM_CACHE_BULK,less,task_struct,KMEM_CACHE_BULK

In [6]:
df = df[['alloc_ip','pid','ptr','size','alloc_jiffies','free_jiffies','free_ip','type','slab','new_type']]
df.head()

,alloc_ip,pid,ptr,size,alloc_jiffies,free_jiffies,free_ip,type,slab,new_type
0,ffffffff81a5ba8f,226,ffff88818dc853f0,176,25383.0,211939.0,00000000deadbeef,KMEM_CACHE_BULK,jbd2_journal_head,KMEM_CACHE_BULK
1,ffffffff817204a4,2203,ffff8881b1640000,4096,48840.0,197120.0,ffffffff816d38f4,ALLOC_PAGES_FOLIO,no-slab,NaN
2,ffffffff817cf984,2348,ffff888185d79b80,320,61904.0,211790.0,ffffffff817cf0b7,KMEM_CACHE_BULK,filp,NaN
3,ffffffff817cf984,2348,ffff888185d78280,320,61906.0,211768.0,ffffffff817cf0b7,KMEM_CACHE_BULK,filp,NaN
4,ffffffff811733c8,2348,ffff8881921a0000,6912,61911.0,196022.0,00000000deadbeef,KMEM_CACHE_BULK,task_struct,KMEM_CACHE_BULK

In [7]:
print('Number of Rows:', len(df))

Number of Rows: 23034390

In [8]:
df.to_csv('mergeddatabase.csv')